name: AutoDependabot

on:
  pull_request:
  push:
    branches:
    - beta-*.*.*

jobs:
  automerge:
    name: Auto-merge patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: mitto98/dependabot-automerge-action@master
        with:
          token: ${{ github.token }}
          merge-patch: true
          
