name: AutoDependabot

on:
  pull_request:
    branches:
    - beta
    - latest
  pull_request_target:
    branches:
    - beta
    - latest

jobs:
  label:
    uses: OpenWonderLabs/.github/.github/workflows/dependabot.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
