name: Stale workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '45 11 * * *'

jobs:
  stale:
    uses: OpenWonderLabs/.github/.github/workflows/stale.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
